[project]
name = "fll-scheduler-ga"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Wonyoung Jang", email = "contact@wonyoungjang.org" }
]
requires-python = ">=3.14"
dependencies = [
    "matplotlib",
    "numpy",
    "pydantic",
    "typer",
]

[project.scripts]
fll-scheduler-ga = "fll_scheduler_ga.entrypoints.cli.__main__:app"

[build-system]
requires = ["uv_build>=0.9.1,<0.10.0"]
build-backend = "uv_build"

[tool.uv.build-backend]
module-name = "fll_scheduler_ga"
module-root = ""

[tool.vulture]
paths = ["./fll_scheduler_ga", "whitelist.py"]
ignore_decorators = ["@app.*"]
min_confidence = 40
verbose = false

[tool.pytest.ini_options]
addopts = [
    "--strict-markers",
    "--strict-config",
    "-ra",
    "-v",
]
testpaths = [
    "tests",
]

[dependency-groups]
dev = [
    "line-profiler",
    "pytest",
    "pytest-cov",
]
docs = []
